### ISSUE TITLE
Erro no encerramento do processamento

### ISSUE THREAD

**Issue by bmelo** [InstitutoDOr/FriendENGINE#1]
Fiz o treinamento do algoritmo SVM com uma sequência funcional e o programa rodou normalmente.
Na sequência seguinte utilizei o SVM para testar as duas classes treinadas e tudo aparenta ter corrido normalmente, porém no encerramento do programa apareceu esta mensagem:

![friend-error](https://cloud.githubusercontent.com/assets/752946/17553405/02ca2e50-5edc-11e6-9389-288c27393816.png)

O problema se repetiu em todas as sequências seguintes de classificação.

**Comment by riddlexter** [comment]
This problem happens in a version not uploaded in github. This problem is already solved. We will create a branch to upload the development version.
